# Generated by Django 4.2.2 on 2024-02-21 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=40, verbose_name='Jurisdiction')),
                ('designation', models.CharField(max_length=40)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-isactive'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30, verbose_name='Public')),
                ('idproof', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publicuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-isactive'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=40, verbose_name='Jurisdiction')),
                ('designation', models.CharField(max_length=40)),
                ('mobile', models.PositiveIntegerField(null=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('officeruser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officeruser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-isactive'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('complainttype', models.CharField(choices=[('Theft', 'Theft'), ('Missing', 'Missing'), ('Public Nuissance', 'Public Nuissance'), ('Attack against women', 'Attack against women')], max_length=40)),
                ('file_up', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('New', 'New'), ('Invalid', 'Invalid'), ('InProgress', 'InProgress'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=10)),
                ('desc', models.TextField()),
                ('Date_occurance', models.DateTimeField(auto_now_add=True)),
                ('place_occurance', models.TextField(default=None)),
                ('assigned_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRMSapp.staff')),
                ('created_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pub_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='CRMSapp.public')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
